/* climate_data.h -- GENERATED by tools/make_inputs.py (built-in demo). DO NOT EDIT BY HAND.
 * Hourly climate inputs for udf/climate_shelter_udf.c  (Leh design day, 21 Dec (demo arrays))
 * Regenerate with your EPW:  python tools/make_inputs.py --epw <file.epw> --day <DOY>
 */
#ifndef CLIMATE_DATA_H
#define CLIMATE_DATA_H

#define N_DATA_HOURS 24
#define TG   8.0      /* deep-ground temperature at 2 m  [C]  */
#define T_START_HR 2.0  /* simulation start hour (2.0 = coldest hour) */
#define WIND_ALPHA 0.16    /* wind power-law exponent */
#define ACH  0.5      /* infiltration air changes per hour */
#define V_ROOM 55.0     /* interior air volume [m3] */
#define V_SOURCE_ZONE 0.6   /* win*_gain fluid-sheet volume [m3] */
#define VENT_K_OPEN 200.0  /* Trombe vent inertial resistance when open [1/m] */
#define AIR_RHO 1.34   /* air density at T_ref [kg/m3] */
#define AIR_CP  1006.0    /* air specific heat [J/kgK] */

/* cell-zone IDs assigned by Fluent (see TUI: /mesh/zones or GUI Outlines->Cell Zones) */
#define ZONE_ID_AIR_INTERIOR 5
#define ZONE_ID_WIN1_GAIN   6
#define ZONE_ID_WIN2_GAIN   7
#define N_CELLS_WIN1 1000   /* update from hourly_audit first-call printout */
#define N_CELLS_WIN2 1000

/* hour-locked climate tables [N_DATA_HOURS] */
static const real TA[24]   = { -13.50, -14.00, -14.20, -14.30, -14.00, -13.20, -12.00, -10.50, -9.00, -7.20, -5.50, -4.00, -2.80, -2.00, -2.20, -3.00, -4.50, -6.50, -8.50, -10.00, -11.20, -12.00, -12.60, -13.10 };
static const real WS[24]   = { 1.20, 1.00, 1.00, 1.00, 1.10, 1.30, 1.60, 2.00, 2.40, 2.80, 3.20, 3.60, 3.80, 3.60, 3.20, 3.00, 3.10, 3.40, 3.00, 2.50, 2.00, 1.60, 1.40, 1.30 };
static const real DNI[24]  = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.0, 300.0, 520.0, 650.0, 720.0, 760.0, 780.0, 770.0, 720.0, 610.0, 380.0, 90.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
static const real DHI[24]  = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 25.0, 55.0, 75.0, 90.0, 100.0, 105.0, 110.0, 108.0, 100.0, 88.0, 65.0, 30.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
/* transmitted solar power per window incl. dynamic SHGC & orientation [W] */
static const real PWIN1[24] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 25.8, 149.7, 129.5, 187.7, 228.9, 252.9, 260.1, 245.0, 207.9, 151.9, 187.0, 43.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
static const real PWIN2[24] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.6, 219.1, 142.7, 152.7, 130.8, 212.9, 152.5, 141.7, 116.5, 82.1, 42.9, 17.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };

#endif /* CLIMATE_DATA_H */
