/*********************************************************************************************
 * climate_shelter_udf.c
 * SIH26051 (DRDO) - Area-Specific Shelter for Thermal Comfort Maintenance
 * ANSYS Fluent transient climate-ingestion UDF suite (serial & parallel, compiled UDF).
 *
 * Tested against long-stable macros only (Fluent 2019R3 .. 2025R1).
 *
 * Provides
 *   DEFINE_PROFILE         ambient_temp_profile      T_amb(t) for Mixed BC / inlet temp (K)
 *   DEFINE_PROFILE         wind_speed_profile        velocity-inlet magnitude, power law (m/s)
 *   DEFINE_PROFILE         wind_conv_profile         exterior film h = 5.7 + 3.8 V (W/m2K)
 *   DEFINE_PROFILE         sky_temp_profile          Swinbank clear-sky temperature (K)
 *   DEFINE_PROFILE         ground_deep_profile       deep-ground temperature (K), soil base
 *   DEFINE_PROFILE         vent_porosity_profile     Trombe vent damper schedule (1/K, 1/m)
 *   DEFINE_SOLAR_INTENSITY direct_from_epw           DNI(t) from EPW table (W/m2)
 *   DEFINE_SOLAR_INTENSITY diffuse_from_epw          DHI(t) from EPW table (W/m2)
 *   DEFINE_SOURCE          win1_solar_gain           dynamic-SHGC transmitted solar power (W/m3)
 *   DEFINE_SOURCE          win2_solar_gain           idem, window 2
 *   DEFINE_SOURCE          ach_infiltration          air-change infiltration loss (W/m3)
 *   DEFINE_INIT            init_shelter              uniform cold start (patch soil after)
 *   DEFINE_EXECUTE_AT_END  hourly_audit              hourly CSV: t[h], T_in avg/min/max (C)
 *
 * Data contract: climate_data.h is REGENERATED by tools/make_inputs.py from your EPW file.
 * It defines arrays TA[], WS[], DNI[], DHI[], PWIN1[], PWIN2[] (N_DATA_HOURS entries) and
 * constants TG, T_START_HR, WIND_ALPHA, ACH, V_ROOM, V_SOURCE_ZONE, VENT_K_OPEN,
 * ZONE_ID_AIR_INTERIOR, ZONE_ID_WIN1_GAIN, ZONE_ID_WIN2_GAIN, N_CELLS_WIN1, N_CELLS_WIN2.
 * A sample (Leh, 21-December design day) ships as udf/climate_data.h.
 *
 * Hook-up (GUI):
 *   - User-Defined -> Functions -> Compiled: compile "libudf", then Load.
 *   - BC dialogs: pick the profile names in Temperature / Velocity Magnitude / H dropdowns.
 *   - Radiation Model -> Solar Load: Direct Solar Irradiation -> direct_from_epw,
 *     Diffuse Solar Irradiation -> diffuse_from_epw.
 *   - Cell zones win1_gain / win2_gain -> Sources -> Energy -> win1_solar_gain / win2_solar_gain.
 *
 * Units: SI. Fluent solves energy in K.  Author: SIH26051 simulation team.
 *********************************************************************************************/

#include "udf.h"

#include "climate_data.h"   /* generated from EPW by tools/make_inputs.py */

/* =========================================================================================
 * Internal helpers
 * ========================================================================================= */

/* Physical time -> fractional hour in the (periodic) data table.
 * T_START_HR lets you start mid-day (e.g. 2.0 h => coldest hour) for clean spin-up. */
static real sim_hour(void)
{
    real t_h = (CURRENT_TIME / 3600.0) + T_START_HR;
    real fh  = fmod(t_h, (real) N_DATA_HOURS);
    if (fh < 0.0)
        fh += (real) N_DATA_HOURS;
    return fh;
}

/* Linear interpolation on an hourly table with wrap-around (periodic day). */
static real interpolate(const real *tbl, real fh)
{
    int i0, i1;
    real f;
    i0 = (int) fh;
    if (i0 >= N_DATA_HOURS) i0 = N_DATA_HOURS - 1;
    i1 = (i0 + 1) % N_DATA_HOURS;
    f  = fh - (real) i0;
    return tbl[i0] + f * (tbl[i1] - tbl[i0]);
}

/* =========================================================================================
 * Boundary profiles
 * ========================================================================================= */

/* Ambient air temperature [K] -- hour-locked across all faces. */
DEFINE_PROFILE(ambient_temp_profile, thread, nv)
{
    face_t f;
    real t_amb_k = C2K(interpolate(TA, sim_hour()));
    begin_f_loop(f, thread)
    {
        F_PROFILE(f, thread, nv) = t_amb_k;
    }
    end_f_loop(f, thread)
}

/* Wind speed [m/s], open-terrain power law V(z) = V10 (z/10)^alpha, z = y (mesh is y-up). */
DEFINE_PROFILE(wind_speed_profile, thread, nv)
{
    face_t f;
    real v10 = interpolate(WS, sim_hour());
    begin_f_loop(f, thread)
    {
        real x[ND_ND], z, vz;
        F_CENTROID(x, f, thread);
        z  = MAX(x[1], 0.10);                      /* floor of 0.1 m avoids 0^a */
        vz = v10 * pow(z / 10.0, WIND_ALPHA);
        F_PROFILE(f, thread, nv) = MAX(vz, 0.25);  /* keep film coefficient sane in calm hours */
    }
    end_f_loop(f, thread)
}

/* Exterior convective film coefficient [W/m2K] for Mixed BC: h_o = 5.7 + 3.8 V (McAdams). */
DEFINE_PROFILE(wind_conv_profile, thread, nv)
{
    face_t f;
    real v10 = interpolate(WS, sim_hour());
    begin_f_loop(f, thread)
    {
        real x[ND_ND], z, vz;
        F_CENTROID(x, f, thread);
        z  = MAX(x[1], 0.10);
        vz = MAX(v10 * pow(z / 10.0, WIND_ALPHA), 0.25);
        F_PROFILE(f, thread, nv) = 5.7 + 3.8 * vz;
    }
    end_f_loop(f, thread)
}

/* Sky temperature [K]: Swinbank clear-sky T_sky = 0.0552 * T_amb^1.5. */
DEFINE_PROFILE(sky_temp_profile, thread, nv)
{
    face_t f;
    real t_sky = 0.0552 * pow(C2K(interpolate(TA, sim_hour())), 1.5);
    begin_f_loop(f, thread)
    {
        F_PROFILE(f, thread, nv) = t_sky;
    }
    end_f_loop(f, thread)
}

/* Deep-ground temperature [K] at the base of the 2 m soil block. */
DEFINE_PROFILE(ground_deep_profile, thread, nv)
{
    face_t f;
    real t_deep_k = C2K(TG);
    begin_f_loop(f, thread)
    {
        F_PROFILE(f, thread, nv) = t_deep_k;
    }
    end_f_loop(f, thread)
}

/* Trombe vent damper: inertial resistance 1/K [1/m] of a porous vent.
 * Open 09:00-17:00 (K = VENT_K_OPEN); night-closed leaves 5 % leakage. */
DEFINE_PROFILE(vent_porosity_profile, thread, nv)
{
    face_t f;
    real h   = sim_hour();
    real of  = (h >= 9.0 && h <= 17.0) ? 1.0 : 0.05;
    real kin = VENT_K_OPEN / MAX(of, 0.05);
    begin_f_loop(f, thread)
    {
        F_PROFILE(f, thread, nv) = kin;
    }
    end_f_loop(f, thread)
}

/* =========================================================================================
 * Solar-load UDFs (Radiation Model dialog -> Solar Load -> Direct/Diffuse Irradiation = udf)
 * Fluent passes the sun unit vector (from the Solar Calculator) and local solar time;
 * magnitudes come from measured EPW data while shadow geometry stays physical.
 * ========================================================================================= */

DEFINE_SOLAR_INTENSITY(direct_from_epw, sun_x, sun_y, sun_z, hour, minute)
{
    real fh = hour + minute / 60.0;
    return MAX(0.0, interpolate(DNI, fh));         /* W/m2, direct normal */
}

DEFINE_SOLAR_INTENSITY(diffuse_from_epw, sun_x, sun_y, sun_z, hour, minute)
{
    real fh = hour + minute / 60.0;
    return MAX(0.0, interpolate(DHI, fh));         /* W/m2, diffuse horizontal */
}

/* =========================================================================================
 * Dynamic-SHGC fenestration (Path A of the guide)
 * make_inputs.py pre-computes, per window, the transmitted solar POWER [W]:
 *   P(t) = SHGC(t) * [ DNI cos(theta_i) f_shade + DHI*0.5 + GHI*rho_g*0.5 ] * A_w
 * The source spreads P(t) uniformly over the thin "gain" fluid sheet inside the window.
 * Set N_CELLS_WINx in climate_data.h (the audit UDF prints the counts on first call).
 * ========================================================================================= */

DEFINE_SOURCE(win1_solar_gain, cell, thread, dS, eqn)
{
    real P = interpolate(PWIN1, sim_hour());       /* W */
    dS[eqn] = 0.0;
    return P / (real) MAX(N_CELLS_WIN1, 1) / C_VOLUME(cell, thread);
}

DEFINE_SOURCE(win2_solar_gain, cell, thread, dS, eqn)
{
    real P = interpolate(PWIN2, sim_hour());
    dS[eqn] = 0.0;
    return P / (real) MAX(N_CELLS_WIN2, 1) / C_VOLUME(cell, thread);
}

/* Air-change infiltration [W/m3] (heating deficit when T_amb < T_in):
 * Q = rho * ACH * V_room / 3600 * cp * (T_amb - T_air), spread over V_SOURCE_ZONE. */
DEFINE_SOURCE(ach_infiltration, cell, thread, dS, eqn)
{
    real t_amb = C2K(interpolate(TA, sim_hour()));
    real t_c   = C_T(cell, thread);
    real m_dot = AIR_RHO * ACH * V_ROOM / 3600.0;                  /* kg/s */
    real q     = m_dot * AIR_CP * (t_amb - t_c) / V_SOURCE_ZONE;   /* W/m3 */
    dS[eqn]    = -m_dot * AIR_CP / V_SOURCE_ZONE;                  /* dQ/dT */
    return q;
}

/* =========================================================================================
 * Initialization: uniform cold start at the coldest hour. Afterwards patch:
 *   soil      -> TG (deep ground), walls -> linear gradient between ambient and TG
 *   (GUI: Adapt -> Cell Register -> patch, or TUI /solve/initialize/set-fm-values)
 * ========================================================================================= */

DEFINE_INIT(init_shelter, domain)
{
    Thread *t;
    cell_t  c;
    real t0 = C2K(interpolate(TA, T_START_HR));

    thread_loop_c(t, domain)
    {
        begin_c_loop_all(c, t)
        {
            C_T(c, t) = t0;
            C_P(c, t) = 0.0;
            C_U(c, t) = 0.0;
            C_V(c, t) = 0.0;
            C_W(c, t) = 0.0;
            C_K(c, t) = 1.0e-4;
            C_D(c, t) = 1.0e-7;
        }
        end_c_loop_all(c, t)
    }
}

/* =========================================================================================
 * Hourly audit logger -> results/audit.csv
 *   columns: time_h, T_in_avg_C, T_in_min_C, T_in_max_C
 * Parallel-safe: cell sums are globally reduced (PRF_GRSUM family); node 0 writes the file.
 * Create the folder 'results' next to your case before running.
 * ========================================================================================= */

DEFINE_EXECUTE_AT_END(hourly_audit)
{
    Domain *domain = Get_Domain(1);
    Thread *t;
    cell_t  c;
    real vol = 0.0, volT = 0.0, tmin = 1.0e30, tmax = -1.0e30;

    t = Lookup_Thread(domain, ZONE_ID_AIR_INTERIOR);
    begin_c_loop_int(c, t)
    {
        real T = C_T(c, t);
        real V = C_VOLUME(c, t);
        vol  += V;
        volT += V * T;
        if (T < tmin) tmin = T;
        if (T > tmax) tmax = T;
    }
    end_c_loop_int(c, t)

#if RP_NODE
    /* parallel: global reductions across compute nodes */
    vol  = PRF_GRSUM1(vol);
    volT = PRF_GRSUM1(volT);
    tmin = PRF_GRLOW1(tmin);
    tmax = PRF_GRHIGH1(tmax);
#endif

    /* log exactly once per simulated hour */
    if (fmod(CURRENT_TIME, 3600.0) < MAX(CURRENT_TIMESTEP, 1.0) && vol > 0.0)
    {
#if RP_NODE
        if (I_AM_NODE_ZERO_P)
        {
            FILE *fp = fopen("results/audit.csv", "a");
            if (fp != NULL)
            {
                fprintf(fp, "%.4f, %.3f, %.3f, %.3f\n",
                        CURRENT_TIME / 3600.0 + T_START_HR,
                        volT / vol - 273.15, tmin - 273.15, tmax - 273.15);
                fclose(fp);
            }
        }
#else
        {
            FILE *fp = fopen("results/audit.csv", "a");
            if (fp != NULL)
            {
                fprintf(fp, "%.4f, %.3f, %.3f, %.3f\n",
                        CURRENT_TIME / 3600.0 + T_START_HR,
                        volT / vol - 273.15, tmin - 273.15, tmax - 273.15);
                fclose(fp);
            }
        }
#endif
    }

    /* first-call diagnostics: print cell counts needed by the win*_gain normalisation */
    if (N_TIME == 0)
    {
        int n1 = 0, n2 = 0;
        t = Lookup_Thread(domain, ZONE_ID_WIN1_GAIN);
        begin_c_loop_int(c, t) { n1++; } end_c_loop_int(c, t)
        t = Lookup_Thread(domain, ZONE_ID_WIN2_GAIN);
        begin_c_loop_int(c, t) { n2++; } end_c_loop_int(c, t)
#if RP_NODE
        n1 = PRF_GISUM1(n1);
        n2 = PRF_GISUM1(n2);
        if (I_AM_NODE_ZERO_P)
            Message("hourly_audit: N_CELLS win1_gain=%d win2_gain=%d (paste into climate_data.h)\n",
                    n1, n2);
#else
        Message("hourly_audit: N_CELLS win1_gain=%d win2_gain=%d (paste into climate_data.h)\n",
                n1, n2);
#endif
    }
}
