#!/usr/bin/env python3
"""
pyfluent_run.py -- SIH26051 shelter: end-to-end ANSYS Fluent automation via PyFluent.

Pipeline (matches docs/SIH26051_Fluent_Setup_Guide.md):
  1. launch Fluent (3d, double precision, N cores)
  2. read  geometry/shelter.cgns   (from geometry/make_shelter_mesh.py)
  3. fix zone types (wind_inlet -> velocity-inlet, outlet_all, ground_ext)
  4. models: Energy, Realizable k-epsilon + Enhanced Wall Treatment, DO radiation +
     Solar Ray Tracing with the Leh solar calculator (transient sun)
  5. create materials, assign cell-zone materials
  6. compile + hook udf/climate_shelter_udf.c (climate profiles, EPW solar intensities,
     dynamic-SHGC gain sources, hourly audit logger)
  7. boundary conditions (mixed h_ext/T_ext/T_sky on the facade, deep-soil BC, wind inlet)
  8. numerics (2nd-order implicit, PRESTO!, coupled), initialization + soil patch
  9. transient run; the UDF writes results/audit.csv every simulated hour
 10. KPIs (T stats, comfort hours, time lag, decrement factor) and a DOE wall-variant
     ranking -> results/doe_ranking.csv

Tested against ansys-fluent-core >= 0.20 with Fluent 2023R2+.
PyFluent/Fluent setting names drift between releases: every fragile call goes through
safe(), which logs failures into MANUAL_STEPS (a printed GUI checklist) instead of dying.

Usage:
  pip install ansys-fluent-core
  python pyfluent_run.py --run-mode demo    # 1 diurnal day (pipeline check)
  python pyfluent_run.py --run-mode full    # 5-day spin-up + 2 recording days
  python pyfluent_run.py --run-mode doe     # 48-h run per wall variant + ranking CSV
"""
import argparse
import csv
import os
import re
import statistics
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MESH = os.path.join(ROOT, "geometry", "shelter.cgns")
UDF_DIR = os.path.join(ROOT, "udf")
RESULTS = os.path.join(ROOT, "results")

# ============================================================== configuration ==============
CFG = dict(
    dt_s=120.0,                 # time step [s]
    iters_per_step=20,          # max iterations per time step
    spinup_days=5,              # full: diurnal spin-up cycles before recording
    record_days=2,              # full: recording days
    demo_hours=24,              # demo: one day
    # solar calculator -- Leh, Ladakh
    latitude=34.16, longitude=77.58, tz=5.5,
    day_of_year=355,            # 21 December
    ground_reflectivity=0.6,    # snow albedo
    # initialization [K]
    t_init=261.0,               # ambient at 02:00 h (coldest hour of the design day)
    t_soil_deep=281.15,         # +8 C at 2 m depth
    op_density=1.34,            # operating density rho(T_amb)
)

MATERIALS = dict(  # name: (density, cp, k), SI  -- PCM variant needs enthalpy data added
    steel_gi=(7850, 460, 50.0),
    puf_80=(35, 1400, 0.022),
    vip_30=(200, 1000, 0.007),
    eps_100=(25, 1400, 0.034),
    concrete_mass=(2300, 880, 1.4),
    pcm_rt24=(800, 2000, 0.2),
    plywood=(550, 2100, 0.13),
    glazing_lowE=(2500, 840, 1.0),
    soil_wet=(1900, 1000, 1.5),
)

ZONE_MATERIALS = {  # baseline design (air zones keep Fluent's default air)
    "wall_steel": "steel_gi", "wall_gap": "concrete_mass", "wall_puf": "puf_80",
    "wall_mass": "concrete_mass", "wall_lining": "plywood",
    "roof_steel_in": "steel_gi", "roof_puf": "puf_80", "roof_steel_out": "steel_gi",
    "floor_ply": "plywood", "floor_puf": "puf_80", "slab_conc": "concrete_mass",
    "soil": "soil_wet", "steel_stud": "steel_gi",
    "glass_win1": "glazing_lowE", "glass_win2": "glazing_lowE",
    "glass_trombe": "glazing_lowE",
}

DOE_VARIANTS = {  # wall-stack comparative analysis demanded by the PS
    "W1_eps_light": {"wall_puf": "eps_100"},
    "W2_baseline": {},
    "W3_pcm_mass": {"wall_mass": "pcm_rt24"},
    "W4_vip": {"wall_puf": "vip_30"},
    "W5_adobe_ref": {"wall_puf": "eps_100"},
}

MANUAL_STEPS = []


def safe(label, fn):
    try:
        fn()
        print(f"  [ok]   {label}")
        return True
    except Exception as exc:
        print(f"  [FAIL] {label}: {exc}")
        MANUAL_STEPS.append(f"{label} -> {exc}")
        return False


# ============================================================== post-processing =============
def parse_climate_header():
    """TA/DNI/DHI/PWIN arrays from udf/climate_data.h (regenerated by make_inputs.py)."""
    txt = open(os.path.join(UDF_DIR, "climate_data.h")).read()
    out = {}
    for key in ("TA", "DNI", "DHI", "PWIN1", "PWIN2"):
        m = re.search(rf"{key}\[24\]\s*=\s*\{{([^}}]*)\}}", txt)
        if m:
            out[key] = [float(v) for v in m.group(1).split(",")]
    return out


def kpis_from_audit(clim):
    """Read results/audit.csv -> temperature KPIs, time lag, decrement factor, comfort."""
    path = os.path.join(RESULTS, "audit.csv")
    if not os.path.exists(path):
        return None
    rows = [r for r in csv.reader(open(path)) if r]
    if len(rows) < 3:
        return None
    t = [float(r[0]) for r in rows]
    tin = [float(r[1]) for r in rows]
    n = len(tin)
    ta = [clim["TA"][int(h) % 24] for h in t]
    # decrement factor + amplitudes over the last diurnal cycle
    seg = tin[-24:] if n >= 24 else tin
    tas = ta[-24:] if n >= 24 else ta
    ti_amp = max(seg) - min(seg)
    ta_amp = max(tas) - min(tas)
    deco = round(ti_amp / ta_amp, 3) if ta_amp > 1e-6 else float("nan")
    # diurnal time lag: lag maximizing correlation of dT_in with dT_ambient
    dtin = [tin[i] - tin[i - 1] for i in range(1, n)]
    dta = [ta[i] - ta[i - 1] for i in range(1, n)]
    best_lag, best_corr = 0, -1e30
    for lag in range(0, min(12, max(2, n // 3))):
        a = dtin[max(0, len(dtin) - 24 - lag): len(dtin) - lag] if lag else dtin[-24:]
        b = dta[-24:]
        if len(a) < 12:
            continue
        ma, mb = statistics.mean(a), statistics.mean(b)
        num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
        den = (sum((x - ma) ** 2 for x in a) * sum((y - mb) ** 2 for y in b)) ** 0.5
        corr = num / den if den > 0 else 0.0
        if corr > best_corr:
            best_corr, best_lag = corr, lag
    solar_kwh = (sum(clim.get("PWIN1", [0])) + sum(clim.get("PWIN2", [0]))) / 1000.0
    return dict(t_in_min_C=round(min(tin), 2), t_in_mean_C=round(sum(tin) / n, 2),
                t_in_max_C=round(max(tin), 2),
                comfort_hours_ge18C=sum(1 for v in tin if v >= 18.0),
                time_lag_h=best_lag, decrement_factor=deco,
                solar_kwh_per_day=round(solar_kwh, 2), hours_simulated=n)


# ============================================================== main ========================
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-mode", choices=["demo", "full", "doe"], default="demo")
    ap.add_argument("--mesh", default=MESH)
    ap.add_argument("--cores", type=int, default=8)
    ap.add_argument("--fluent-version", default=None, help="e.g. '24.2'")
    a = ap.parse_args()

    os.makedirs(RESULTS, exist_ok=True)
    audit_path = os.path.join(RESULTS, "audit.csv")
    if os.path.exists(audit_path):
        os.remove(audit_path)

    import ansys.fluent.core as pyfluent
    print("launching Fluent ...")
    kw = dict(mode="solver", precision="double", processor_count=a.cores,
              start_transcript=False, show_gui=False)
    if a.fluent_version:
        kw["product_version"] = a.fluent_version
    solver = pyfluent.launch_fluent(**kw)

    # ---- 1. mesh ---------------------------------------------------------------
    print("reading mesh:", a.mesh)
    safe("read mesh (cgns)", lambda: solver.tui.file.read_mesh(f'"{a.mesh}"'))
    safe("check mesh", lambda: solver.tui.mesh.check())

    # ---- 2. zone types ----------------------------------------------------------
    print("zone types ...")
    for zone, ztype in (("wind_inlet", "velocity-inlet"),
                        ("outlet_all", "pressure-outlet"),
                        ("ground_ext", "symmetry")):
        safe(f"{zone} -> {ztype}", lambda z=zone, t=ztype:
             solver.setup.boundary_conditions.set_zone_type(zone_list=[z], new_type=t))

    # ---- 3. models -----------------------------------------------------------------
    print("models ...")
    models = solver.setup.models
    safe("energy on", lambda: setattr(models.energy, "enabled", True))
    safe("k-epsilon family", lambda: setattr(models.viscous, "model", "k-epsilon"))
    safe("realizable variant", lambda: setattr(models.viscous.k_epsilon_model,
                                               "k_epsilon_model", "realizable"))
    safe("enhanced wall treatment", lambda: solver.tui.define.models.viscous
         .near_wall_treatment.enhanced_wall_treatment("yes"))
    safe("DO radiation", lambda: setattr(models.radiation, "model",
                                         "discrete-ordinates"))
    safe("DO pixel divisions 4x8", lambda: (
        setattr(models.radiation.discrete_ordinates, "theta_divisions", 4),
        setattr(models.radiation.discrete_ordinates, "phi_divisions", 8)))
    safe("solar ray tracing", lambda: setattr(models.radiation.solar_load,
                                              "model", "solar-ray-tracing"))
    lat, lon, tz = CFG["latitude"], CFG["longitude"], CFG["tz"]
    doy, rho_g = CFG["day_of_year"], CFG["ground_reflectivity"]
    safe("solar calculator (Leh)", lambda: solver.tui.define.models.radiation
         .solar_parameters.solar_calculator(
             "no", "no", "no", str(lat), str(lon), str(tz),
             "n", "y", "0", "0", "1", "1", "0", "0", str(doy), str(rho_g)))

    # ---- 4. materials -----------------------------------------------------------------
    print("materials ...")
    mats = solver.setup.materials

    def make_solid(name, rho, cp, k):
        try:
            mats.solid[name]                      # exists?
        except Exception:
            mats.solid.create(name)
        mats.solid[name].density = rho
        mats.solid[name].specific_heat = cp
        mats.solid[name].thermal_conductivity = k

    for name, (rho, cp, k) in MATERIALS.items():
        safe(f"material {name}", lambda n=name, r=rho, c=cp, kk=k: make_solid(n, r, c, kk))

    # ---- 5. cell zones -------------------------------------------------------------------
    print("cell zone materials ...")
    cz = solver.setup.cell_zone_conditions
    for zone, mat in ZONE_MATERIALS.items():
        safe(f"{zone} -> {mat}", lambda z=zone, m=mat:
             setattr(cz.solid[z].general, "material", m))

    # ---- 6. UDF ---------------------------------------------------------------------------
    print("UDF compile & hook ...")
    src = os.path.join(UDF_DIR, "climate_shelter_udf.c")
    safe("compile libudf", lambda: solver.tui.define.user_defined.compiled_functions
         .compile("libudf", f'"{src}"'))
    safe("load libudf", lambda: solver.tui.define.user_defined.compiled_functions
         .load("libudf"))
    safe("hook direct_from_epw", lambda: solver.tui.define.models.radiation
         .solar_parameters.direct_solar_irradiation('"direct_from_epw"'))
    safe("hook diffuse_from_epw", lambda: solver.tui.define.models.radiation
         .solar_parameters.diffuse_solar_irradiation('"diffuse_from_epw"'))
    for w in (1, 2):
        safe(f"win{w} gain source", lambda ww=w: setattr(
            cz.fluid[f"win{ww}_gain"].sources, "energy",
            {f"win{ww}_solar_gain": dict(value=None, udf=True)}))

    # ---- 7. boundary conditions -------------------------------------------------------------
    print("boundary conditions ...")
    bcs = solver.setup.boundary_conditions

    def set_mixed(zone):
        w = bcs.wall[zone]
        w.thermal.thermal_bc = "mixed"
        w.thermal.heat_transfer_coefficient = "wind_conv_profile"
        w.thermal.temperature = "ambient_temp_profile"
        w.thermal.outside_temperature = "ambient_temp_profile"
        w.thermal.wall_ext_rad_temperature = "sky_temp_profile"
        w.thermal.material = "steel_gi"

    safe("facade_ext mixed BC (profiles)", lambda: set_mixed("facade_ext"))
    safe("soil_far deep-ground BC", lambda: (
        setattr(bcs.wall["soil_far"].thermal, "thermal_bc", "temperature"),
        setattr(bcs.wall["soil_far"].thermal.thermal_condition, "temperature",
                "ground_deep_profile")))
    safe("wind inlet profiles", lambda: (
        setattr(bcs.velocity_inlet["wind_inlet"].momentum, "velocity_magnitude",
                "wind_speed_profile"),
        setattr(bcs.velocity_inlet["wind_inlet"].thermal, "temperature",
                "ambient_temp_profile")))
    MANUAL_STEPS.append("Glazing (int_glass_win1/2, glass_trombe_out): set semi-transparent "
                        "two-band DO properties per guide S7 (GUI: wall -> Radiation tab).")
    MANUAL_STEPS.append("trombe_absorber: opaque, solar absorptivity 0.94 (Radiation tab).")
    MANUAL_STEPS.append("Verify cell-zone IDs from /mesh/zones and paste into climate_data.h, "
                        "then recompile libudf.")

    # ---- 8. numerics --------------------------------------------------------------------------
    print("numerics ...")
    gen = solver.setup.general
    safe("transient 2nd-order", lambda: setattr(gen.solver, "time",
                                                "unsteady-2nd-order"))
    safe("gravity -y", lambda: (setattr(gen, "gravity", True),
                                setattr(gen.gravity_components, "y", -9.81)))
    safe("operating density", lambda: solver.tui.define.operating_conditions
         .operating_density(str(CFG["op_density"])))
    meth = solver.solution.methods
    safe("PRESTO! pressure", lambda: setattr(meth.discretization_scheme, "pressure",
                                             "presto!"))
    safe("coupled P-V", lambda: setattr(meth.p_v_coupling.flow_scheme, "coupled", True))
    safe("2nd-order energy", lambda: setattr(meth.discretization_scheme, "energy",
                                             "second-order-upwind"))

    # ---- 9. report definitions -----------------------------------------------------------------
    print("report definitions ...")
    rds = solver.solution.report_definitions

    def vol_report(name, rtype, zone):
        r = rds.create(name)
        r.report_type = rtype
        r.field = "temperature"
        r.zone_names = [zone]

    def flux_report(name, zone):
        r = rds.create(name)
        r.report_type = "surface-integral"
        r.field = "total-surface-heat-flux"
        r.surface_names = [zone]

    safe("report T_in_avg", lambda: vol_report("t-in-avg", "volume-average",
                                               "air_interior"))
    safe("report T_in_min", lambda: vol_report("t-in-min", "volume-min",
                                               "air_interior"))
    safe("report T_in_max", lambda: vol_report("t-in-max", "volume-max",
                                               "air_interior"))
    for nm, zn in (("q-envelope", "int_envelope"), ("q-win1", "int_glass_win1"),
                   ("q-win2", "int_glass_win2")):
        safe(f"report {nm}", lambda n=nm, z=zn: flux_report(n, z))

    # ---- 10. initialization ----------------------------------------------------------------------
    print("initialization ...")
    init = solver.solution.initialization

    def do_init():
        init.initialization_type = "standard"
        init.standard_initialize.hybrid_init = False
        init.standard_initialize.temperature = CFG["t_init"]
        init.standard_initialize()

    safe("standard init at t_init", do_init)
    safe("patch soil to deep T", lambda: solver.tui.solve.initialize.set_fm_values(
        "temperature", str(CFG["t_soil_deep"]), "soil()"))

    # ---- 11. autosave + run ------------------------------------------------------------------------
    safe("autosave every 2 h", lambda: solver.tui.file.auto_save(
        "case-data", "2", f'"{os.path.join(RESULTS, "shelter_auto")}"'))

    def run(hours):
        steps = int(hours * 3600.0 / CFG["dt_s"])
        safe("transient controls", lambda: (
            solver.tui.solve.set.transient_controls.set_time_step(str(CFG["dt_s"])),
            solver.tui.solve.set.transient_controls.max_iter_per_time_step(
                str(CFG["iters_per_step"]))))
        t0 = time.time()
        safe(f"run {hours:g} h ({steps} steps)",
             lambda: solver.tui.solve.dual_time_iterate(str(steps)))
        print(f"  wall time: {(time.time() - t0) / 60:.1f} min")

    if a.run_mode == "demo":
        run(CFG["demo_hours"])
    elif a.run_mode == "full":
        run(24 * CFG["spinup_days"])
        run(24 * CFG["record_days"])
    elif a.run_mode == "doe":
        run(48.0)          # 1 spin-up day + 1 recording day per variant

    # ---- 12. KPIs & DOE ranking ----------------------------------------------------------------------
    clim = parse_climate_header()
    kpi = kpis_from_audit(clim)
    print("\nBaseline KPIs:", kpi)

    if a.run_mode == "doe":
        rows = []
        for variant, overrides in DOE_VARIANTS.items():
            print(f"\nDOE variant {variant}: {overrides}")
            for zone, mat in overrides.items():
                safe(f"{zone} -> {mat}", lambda z=zone, m=mat:
                     setattr(cz.solid[z].general, "material", m))
            if os.path.exists(audit_path):
                os.remove(audit_path)
            run(48.0)
            k = kpis_from_audit(clim) or {}
            rows.append(dict(variant=variant, **k))
        with open(os.path.join(RESULTS, "doe_ranking.csv"), "w", newline="") as fh:
            wr = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            wr.writeheader()
            wr.writerows(rows)
        rows.sort(key=lambda r: (-(r.get("comfort_hours_ge18C") or 0),
                                 r.get("t_in_min_C") or -99))
        print("\nRANKING (most efficient first):")
        for r in rows:
            print("  ", r)

    safe("save final case+data", lambda: solver.tui.file.write_case_data(
        f'"{os.path.join(RESULTS, "shelter_final")}"'))
    solver.exit()

    if MANUAL_STEPS:
        print("\nMANUAL STEPS (version-specific API drift) -- finish in the GUI:")
        for s in MANUAL_STEPS:
            print("  -", s)
    print("\nDone. Artifacts: results/audit.csv, results/*.cas.h5; guide Sec. 12-13.")


if __name__ == "__main__":
    main()
